import "./globals.css";

import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
//import { Space_Grotesk } from "next/font/google";
import { Roboto_Mono } from "next/font/google";

//const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] });
const robotoMono = Roboto_Mono({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="dark"
    >
      <body className={robotoMono.className}>
        <div className="grid min-h-screen place-content-center bg-blue-50 px-4 dark:bg-blue-950">
          <div className="sm:w-[500px] md:w-[600px] lg:w-[700px] ">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
